In [26]:
import pandas as pd

data = [1,3,5,7,9]
data_2 = [2,4,6,8,10]
s = pd.Series(data) #1차원 자료구조 Series
d = pd.Series(data_2)

In [27]:
(s*d)

0     2
1    12
2    30
3    56
4    90
dtype: int64

In [10]:
data = {
    'year' : [2016,2017,2018],
    'GDP rate': [2.8, 3.1, 3.0],
    'GDP': ['1.637M', '1.73M', '1.83M']
    
}
df = pd.DataFrame(data) # 2차원 자료구조 DataFrame = {'':[], ...}

In [12]:
df

   year  GDP rate     GDP
0  2016       2.8  1.637M
1  2017       3.1   1.73M
2  2018       3.0   1.83M

In [33]:
# import pandas as pd
# import numpy as np

# data = np.random.rand(2,3,4)
# p = pd.Panel(data)
# print(p)
data = np.random.randint(1, 10, (5, 3, 2))
pnl = pd.Panel(
    data, 
    items=['item {}'.format(i) for i in range(1, 6)], 
    major_axis=[2015, 2016, 2017], 
    minor_axis=['US', 'UK']
)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version

TypeError: Panel() takes no arguments

In [47]:
dates = pd.date_range('20130101', periods=6)
dates

df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))
df

                   A         B         C         D
2013-01-01  0.124765 -1.837272  0.514306 -0.851458
2013-01-02  0.417783 -1.135335  0.565743 -0.872256
2013-01-03 -0.346786  1.179379  0.388376  1.632730
2013-01-04  0.924733 -1.266115  0.023893 -0.410330
2013-01-05 -0.520025  2.725950 -0.406966 -0.580995
2013-01-06 -0.224832  0.605136 -0.347700 -0.098057